### ISSUE TITLE
Question about pem files

### ISSUE THREAD

**Issue by adelburekovic** [andris9/mobileconfig#12]
I am trying to create signed wifi mobileconfig file but I have issues with getting the .pem files. Where exactly on the apple development center can I find them? Do I need to convert .cert to pem or? I checked the guide on signing but couldn't get any further.

Any tip would be helpful

Thanks

**Comment by craftbyte** [comment]
@adelburekovic If you are running on a Mac you get them in XCode when you try to sign your first app. You can then find them in Keychain Access  with the name "Developer ID". You should know though that Apple allows any certificate that is trusted by the system to sign mobileconfig's. It may be easier to use something like Let's Encrypt to get the job done.

**Comment by andris9** [comment]
I’ve also used Let’s Encrypt certificates. The thing to consider though is that profile considered is valid as long as the certificate is valid and LE certs have a short life span (max 3 mo). Everything should keep working once the cert expires but checking installed profile info should start showing “unverified” or smth
