### ISSUE TITLE
Define accounts full name in getSignedEmailConfig()?

### ISSUE THREAD

**Issue by lars-str** [andris9/mobileconfig#13]
Hey guys,
after creating a mobileconfig (based on examples/imap.js file) and executing it on a iOS device, iOS is asking for the full name (which is used as the sender name) of the installed account. Is it possible to define it in the configuration so that the user only needs to install the config without specifying anything?

Thanks!

**Comment by andris9** [comment]
I think it should work if you define `emailAccountName` option.
