### ISSUE TITLE
msgid all 0

### ISSUE THREAD

**Issue by van-scott** [andris9/mobileconfig#18]
The msgid of the DNS request sent by installing mobileconfig is all 0, which causes formaterr to appear easily when the concurrency is high. Is there any configuration to set the msgid to be randomly generated?

**Comment by andris9** [comment]
Could you elaborate, I don't really get it? What msgid and dns request?

**Comment by van-scott** [comment]
sorry，It may not be suitable to raise this question here, this is a dns problem
