### ISSUE TITLE
Is it possible to turn this onto iOS

### ISSUE THREAD

**Issue by weahoo** [andris9/mobileconfig#2]
I noticed this project using the jsrsasign to sign the mobileconfig, and would like to turn it onto iOS. May I know whether it is possible from your perspective? I knew this is based on Node.js and dependent on many modules, if you can instruct me the kern script you are using in jsrasign module, it would be appreciated. Basically I don't expect using so many algorithms to sign a mobileconfig, one is sufficient, but I didn't want to only sign a CADV or Imap configuration, but a general configuration, such as VPN profile.
Look forward to your comments.

Yuexin

**Comment by andris9** [comment]
mobileconfig files are signed [CMS](https://en.wikipedia.org/wiki/Cryptographic_Message_Syntax) files. jsrsasign has nothing unique in it, you could just as well use [openssl cms -sign](https://www.openssl.org/docs/man1.0.0/apps/cms.html) for it. I have no idea how to do this in iOS though.
