### ISSUE TITLE
Not supported argument

### ISSUE THREAD

**Issue by TheSinding** [andris9/mobileconfig#4]
Hey, I'm trying out your basic example, but I'm getting a the "Not supported argument" any idea why?..
Is it the key? Do I need one ?

**Comment by TheSinding** [comment]
Never mind I got it working :) Thanks, awesome job :+1:

**Comment by mandeepm91** [comment]
@TheSinding I also got the same issue. How did you resolve this ?

**Comment by mandeepm91** [comment]
Nevermind. I am trying the `getEmailConfig` for now and it works fine
