### ISSUE TITLE
Add support for VPN config

### ISSUE THREAD

**Issue by OmgImAlexis** [andris9/mobileconfig#5]
On iOS to enable "always on" mode for certain types of VPNs requires a mobileconfig.

Would you be able to add support for this?

Ref: https://apple.stackexchange.com/a/249161/130438

**Comment by andris9** [comment]
Yeah, I see the issue. There are other types of stuff as well besides VPN that can be packaged as a mobileconfig file. Currently the supported formats use separate template files to generate plist output but to add more template files does not seem feasible. It would be better to switch over for generating plist files programmatically using the already available plist module. I'm not sure though when I will have time for this but in general I'm in favor of making it able to extend this library.

**Comment by andris9** [comment]
I think that I'll just add a generic method that can be used to create signed plist content from whatever structured data. That way you'd have to list all options that are needed for the VPN config yourself.

**Comment by andris9** [comment]
@OmgImAlexis I added the generic method, see details [here](https://github.com/andris9/mobileconfig#generate-and-sign-any-configuration). Basically you'd have to provide the exact configuration file content as a structured object and it will be converted to plist format and signed. You have to figure out the needed keys yourself, I hope the email example helps though.
